#cloud-config
package_update: true
packages:
  - ruby-full
  - ruby-bundler
  - build-essential
  - mongodb
  - git
runcmd:
  - sudo systemctl start mongodb
  - sudo systemctl enable mongodb
  - sudo git clone -b monolith https://github.com/express42/reddit.git /home/yc-user/reddit
  - cd /home/yc-user/reddit && bundle install
  - puma -d

datasource:
 Ec2:
  strict_id: false
ssh_pwauth: no
users:
- name: yc-user
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTdeHy0cPddPZyfhd1ClMhxbjPYzH6UtK3f0vkm4fqpBUcw0iNPuvbg+wn5Uv/+p8+hJaOoiq4eJUplHEE/l+yt1TqiO4AP8JLFAr60RoIrrBdJSQESj5s8hL3XWdkP0MghkkYVTzdfgD6vb/Ji24SEeiqiqZVoqd6yFHm593tRV1fk1VQ1To9ZjtpjCfCZH4tnnpvfrQ980SVczYrjFQ+W2tc3Zu5U8fMTzV+f6Xh6r1b01pU+m3tobVXgznaCInOnDzej4iJ1IJ95tMoJ5QNTOXa9M81S5YVGTUHAOG/U0OgH+jaT3Q4QS/iyRI5VJ2gngRKp3RJaOSxBGcyLIdAG/1eOcx20KD4KG5RrrsHDbKueeqJmcD3jiLWB4qVSlBmcSrGzI2RyTNDSg4JEygVx32YPQtaC6o0u5eUOeB7XGT43qknm3PygwJwujGmK02/+dfWC+bhju0DxQxffhj7LmLKwTQp2zPlevEca76CwP/DsIi5Oij/BpqmpkwedKk= kita@server
