---
- name: Install soft for app
  hosts: all
  become: true

  tasks:
    - name: Install ruby
      apt:
        name: ruby-full
        state: present

    - name: Install bundler
      apt:
        name: ruby-bundler
        state: present

    - name: Install build-essential
      apt:
        name: build-essential
        state: present
