---
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Add unit file for Puma
  copy:
    src: reddit.service
    dest: /etc/systemd/system/reddit.service
  tags: app-tag
  notify: start reddit.service

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/ubuntu/db_config
    mode: 0644

- name: Install Git
  apt:
    name: git
    state: latest
