---
- name: Configure App
  hosts: app
  become: yes
  vars:
    db_host: "{{ db_ip }}"
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/reddit.service
        dest: /etc/systemd/system/reddit.service
      tags: app-tag
      notify: start reddit.service

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        mode: 0644

    - name: Install Git
      apt:
        name: git
        state: latest


  handlers:
    - name: start reddit.service
      become: true
      service:
        name: reddit.service
        state: started
        enabled: yes

    - name: restart reddit.service
      become: true
      service:
        name: reddit.service
        state: restarted
