---
- name: Configure DB
  hosts: db
  become: yes
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongodb.conf.j2
        dest: /etc/mongodb.conf
        mode: 0644
      notify: restart mongodb

  handlers:
    - name: restart mongodb
      become: true
      service:
        name: mongodb
        state: restarted
